### ISSUE TITLE
iOS text issue

### ISSUE THREAD

**Issue by kParkz** [alexolivero/Obscurify#5]
There is no space between "Hi" and "(user's Spotify name)" when a user logs in on an iPhone. Tested with multiple iPhones. For example: https://imgur.com/a/lfNVril

**Comment by alexolivero** [comment]
Hey prduren, thanks for bringing this to my attention! Could you please
check again, it should be fixed.

**Comment by kParkz** [comment]
Just checked on an iPhone 6 and 7, the issue is still there!

**Comment by kParkz** [comment]
Works now! just checked again
